# -*- coding: utf-8 -*-
"""python assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUOf7NH3FM80TtHNMI0Xl_DjuYUTUM6Z

# **Python Assignments: -**

# 1.Print all prime numbers between input range (Ex – input 20 50, prints all prime numbers between 20 and 50).
"""

m=int(input("Enter m value: "))
n=int(input("Enter n value: "))
for v in range(m,n+1):
  count=0
  for i in range(1,v+1):
    if(v%i==0):
      count+=1
  if(count==2):
    print(v,end=" ")

"""

#2. Factorial using recursion
"""

def fact(n):
  if n==0:
    return 1
  return n*fact(n-1)
n=int(input("Enter the value:"))
print(fact(n))

"""# 3.Square of numbers using lambda"""

n=int(input("Enter the value"))
square=lambda x:x*x
print("Square value is:" ,square(n))

"""# 4.Find the second largest element in a list"""

a=list(map(int,input("Enter the value:").split()))
largest=a[0]
second=a[0]
for x in a:
  if x>largest:
    second=largest
    largest=x
  elif x>second and x!=largest:
    second=x
print(second)

"""# 5.Count frequency of characters in a string"""

s = input()

for ch in s:
    count = 0

    for x in s:
        if ch == x:
            count += 1

    print(ch, count)

"""# 6.Calculate area of a circle using math library."""

import math

r = float(input("enter the value:"))

area = math.pi * r * r

print(area)

"""# 7.Reverse a string without using built‑in reverse"""

s = input("enter the value: ")

reverse = ""

for ch in s:
    reverse = ch + reverse

print(reverse)

"""# 8. Remove Duplicates From List"""

a = list(map(int, input("Enetr the value: ").split()))

b = []

for x in a:
    if x not in b:
        b.append(x)

print(b)

"""# 9. Merge Two Dictionaries"""

a = {"a": 1, "b": 2}
b = {"c": 3, "d": 4}

for key in b:
    a[key] = b[key]

print(a)

"""# 10. Fibonacci Using Recursion"""

def fibonacci(n):
    if n <= 1:
        return n

    return fibonacci(n - 1) + fibonacci(n - 2)

n = int(input())

for i in range(n):
    print(fibonacci(i), end=" ")

"""# **# Python Function Assignments:**

# 1.Write a function calculate(a, b, operation) that performs addition, subtraction, multiplication, or division based on the supplied operation.
"""

def calculate(a, b, operation):
    if operation == "+":
        return a + b
    elif operation == "-":
        return a - b
    elif operation == "*":
        return a * b
    elif operation == "/":
        return a / b

a = int(input("Enter a: "))
b = int(input("Enter b: "))
operation = input("Enter operation: ")

print("values:",calculate(a, b, operation))

"""# 2.Write a function sum_numbers(*args) that accepts any number of arguments and returns their sum."""

def sum_numbers(*args):
    total = 0

    for x in args:
        total = total + x

    return total

print(sum_numbers(10, 20, 30))

"""
# 3.Write a function employee(**args) that accepts employee information such as name, ID, department and salary, then displays the information."""

def employee(**args):
    for key, value in args.items():
        print(key, ":", value)

employee(name="Vaishu", ID=101, department="IT", salary=30000)

"""# 4.Write a function remove_duplicates(lst) that returns a list containing only unique elements while preserving their original order."""

def remove_duplicates(lst):
    result = []

    for x in lst:
        if x not in result:
            result.append(x)

    return result

a = [1, 2, 2, 3, 1, 4]

print(remove_duplicates(a))

"""# 5.Using a lambda function, sort a list of tuples based on the second element. Example: [(1,5), (2,3), (4,1)]."""

a = [(1, 5), (2, 3), (4, 1)]

a.sort(key=lambda x: x[1])

print(a)

"""# **NUMPY ASSIGNMENT**

# Question 1 – Student Marks Array
"""

import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Array:", marks)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data Type:", marks.dtype)
print("Dimensions:", marks.ndim)

"""# 2. Student Marks Access"""

import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("First student:", marks[0])
print("Third student:", marks[2])

print("First three marks:", marks[0:3])
print("Last two marks:", marks[3:5])

"""# 3. Subject-wise Marks"""

import numpy as np

marks = np.array([78,85,90,65,72,80,88,91,84,56,62,70,95,89,92])

matrix = marks.reshape(5,3)

print(matrix)

"""# 4. Internal and External Marks"""

import numpy as np

internal = np.array([20, 18, 25, 22, 19])
external = np.array([60, 55, 65, 58, 62])

final = internal + external

print(final)

"""# 5. Pass Percentage Analysis"""

import numpy as np

marks = np.array([45, 78, 56, 32, 91])

pass_students = marks >= 50

print(pass_students)
print(marks[pass_students])

"""# 6. Average Marks"""

import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

avg = np.mean(marks, axis=1)

print(avg)

"""# 7. Class Performance Statistics"""

import numpy as np

marks = np.array([67,82,91,74,58])

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

"""# 8. Subject-wise Performance"""

import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

subject_total = np.sum(marks, axis=0)

print(subject_total)

"""# 9. Student-wise Performance"""

import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

student_total = np.sum(marks, axis=1)

print(student_total)

"""# 10. Student Ranking"""

import numpy as np

marks = np.array([245,278,219,290,256])

sorted_marks = np.sort(marks)

print("Sorted:", sorted_marks)

rank = np.argsort(marks)

print("Rank Index:", rank)

"""# 11. Duplicate Marks Analysis"""

import numpy as np

marks = np.array([85,92,85,76,92])

unique_marks = np.unique(marks)

print(unique_marks)

"""# 12. Missing Marks"""

import numpy as np

marks = np.array([78,85,np.nan,92,67])

avg = np.nanmean(marks)

print(avg)

"""# 13 – Grade Classification"""

import numpy as np

marks = np.array([95,82,74,61,45])

for m in marks:
    if m >= 90:
        print(m, "A")
    elif m >= 75:
        print(m, "B")
    elif m >= 60:
        print(m, "C")
    else:
        print(m, "D")

"""# 14. Random Marks Generation"""

import numpy as np

marks = np.random.randint(40,100,5)

print("Marks:", marks)

print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

"""# 15 – Complete Student Analysis"""

import numpy as np

marks = np.array([
    [78,85,90],
    [65,72,80],
    [88,91,84],
    [56,62,70],
    [95,89,92]
])

total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)

highest = np.max(marks, axis=1)

lowest = np.min(marks, axis=1)

class_avg = np.mean(total)

print("Total:", total)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)

print("Class Average:", class_avg)

print("Above Class Average:")

for i in range(len(total)):
    if total[i] > class_avg:
        print("Student", i+1)